FROM nginx:alpine

# Copy your static files
COPY style.css /usr/share/nginx/html/
COPY login-style.css /usr/share/nginx/html/
COPY index.html /usr/share/nginx/html/
COPY login.html /usr/share/nginx/html/
COPY app.js     /usr/share/nginx/html/

EXPOSE 80
